config/routes.rb
Rails.application.routes.draw do
  resources :books

end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books=Book.all
    @book_No=0
  end

  def show
    @book=Book.find_by(id: params[:id])
    @book_No = params[:book_id]
  end
  def new
    @book =Book.new
  end
  
  def create
    @book =Book.new
    @book.name=params[:book][:name]
    @book.date=params[:book][:date]
    @book.star=params[:book][:star]
    @book.impression=params[:book][:impression]
    @book.save
    redirect_to books_path ,notice: '新しい本を追加しました！'
  end
  def edit
    @book=Book.find_by(id: params[:id])
    
  end
  def update
    @book=Book.find_by(id: params[:id])
    @book.name=params[:book][:name]
    @book.date=params[:book][:date]
    @book.star=params[:book][:star]
    @book.impression=params[:book][:impression]
    @book.save
    redirect_to books_path,notice: '本を編集しました！'
  end
  def destroy
    @book=Book.find_by(id: params[:id])
    @book.destroy
    redirect_to books_path, notice: '本を削除しました！'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<p>ここは本を編集するページです。</p>

<%= form_for(@book)do |f| %>

 <div class="f.submit">
  <%= f.label :タイトル %><br>
  <%= f.text_field :name %>
 </div>
 <div class="f.submit">
  <%= f.label :読んだ本 %><br>
  <%= f.text_field :name %>
 </div>
  <div class="f.submit">
  <%= f.label :評価（☆マーク） %><br>
  <%= f.text_field :name %>
 </div>
 <div class="f.submit">
  <%= f.label :感想 %><br>
  <%= f.text_area :impression, cols: 40, rows: 20%>
 </div>

 <div class="actions">
  <%= f.submit '編集する'%>
 </div>
<% end %>
<%= link_to'編集せずに戻る',books_path,target: "_brank" %>
<%=button_to'削除',book_path(id: @book.id),method: :delete,data: { confirm: '本当に削除しますか?'}%>

app/views/books/index.html.erb
<p id="notice"><%= flash[:notice] %></p>
<h1><span class="glyphicon glyphicon-book" aria-hidden="true"></span>童話ブック</h1>
<p>読んだ本をまとめるサイトです。</p>
<p>詳しい情報は名前をクリックしてください。</p>
<%= link_to'新しい本を登録する',new_book_path,target: "_brank" %>
<div class='row'>
   <% for b in @books %>
      <%@book_No = @book_No+1%>
       <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
         <h4>No.<%=@book_No%> : <%= b.name%></h4>
         <p>登録日<%= b.created_at%></p>
         <p>最終更新日<%= b.updated_at%></p>
         <%= link_to 'くわしく見る', book_path(id: b.id,book_id: @book_No),target: "_brank" %>
       </div>
     <% end %>
</div>

app/views/books/new.html.erb
<p>ここは本を登録するページです。</p>

<%= form_for(@book)do |f| %>

 <div class="field">
  <%= f.label :タイトル %><br>
  <%= f.text_field :name %>
 </div>
 <div class="field">
  <%= f.label :読んだ本 %><br>
  <%= f.text_field :date %>
 </div>
 <div class="field">
  <%= f.label :評価（☆マーク） %><br>
  <%= f.text_field :star %>
 </div>
 <div class="field">
  <%= f.label :感想 %><br>
  <%= f.text_area :impression, cols: 40, rows: 20%>
 </div>

 <div class="actions">
  <%= f.submit '登録' %>
 </div>
<% end %>
<%= link_to'トップに戻る',books_path,target: "_brank" %>

app/views/books/show.html.erb
<h1><%= @book.name %></h1>
<p>No：<%= @book_No %></p>
<p>読んだ日：<%= @book.date %></p>
<p>評価：<%= @book.star %></p>
<p>感想：<%= @book.impression %></p>
<%= link_to'トップに戻る',books_path,target: "_brank" %>
<%= link_to'内容を変更する',edit_book_path(id: @book.id),target: "_brank" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-inverse">
    <div class="container">
      <%= link_to '童話ブック', books_path, class: "navbar-brand"%>
      <ul class="nav navbar-nav navbar-right">
        <li><%=link_to books_path do %>
              <span class="glyphicon glyphicon-home" aria-hidden="true"></span> トップに戻る
            <% end %>
        </li>
        <li><%=link_to new_book_path do %>
              <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> 本を追加する
            <% end %>
        </li>
        <li><%=link_to books_path do %>
              <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span> ログインする
            <% end %>
        </li>
        
      </ul>
    </div>
  </header>
  <div class="container">
      <%= yield %>
  </div>
</body>
</html>